<div class="alert alert-info">
<font size="5"><b>Комментарий ревьюера 2</b></font>

Привет еще раз. Спасибо, что доделал работу. Оформление комментариев по работе сохраняется. Только обозначим, что это вторая итерация. 

</div>

<div class="alert alert-info">
<font size="5"><b>Комментарий ревьюера</b></font>

Привет, Андрей! Спасибо, что прислал задание:) Поздравляю с первым сданным проектом! Меня зовут Слепцов Артем и я буду проверять твой проект) Ты проделал большую работу над проектом. Он выполнен уже на достойном уровне. Однако есть моменты, которые еще можно улучшить. Будет здорово, если ты, надеюсь, не против, если я буду на ты, будешь отвечать на комментарии и участвовать в диалоге. Если обращение на ты неприемлемо, то прошу сообщить. 

Мои комментарии обозначены пометкой **Комментарий ревьюера**. Далее в файле ты сможешь найти их в похожих ячейках:
    
<div class="alert alert-success">Успех: Если фон комментария зелёный - всё сделано правильно. Рекомендации укажу таким же цветом;</div>
        
<div class="alert alert-warning">Совет: Оранжевый - некритичные замечания;</div>
        
<div class="alert alert-danger">Ошибка: Красный - нужно переделать. </div>
        
Не удаляй эти комментарии и постарайся учесть их в ходе выполнения данного проекта. Свои же комментарии ты можешь обозначать любым заметным способом. 

</div>

# Исследование надёжности заёмщиков

Заказчик — кредитный отдел банка. Нужно разобраться, влияет ли семейное положение и количество детей клиента на факт погашения кредита в срок. Входные данные от банка — статистика о платёжеспособности клиентов.

Результаты исследования будут учтены при построении модели **кредитного скоринга** — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.

<div class="alert alert-warning">
<font size="5"><b>Комментарий ревьюера</b></font>

Совет: Правильно, что есть краткое вступление в работу, описание того, что надо делать. В работе следует приводить информацию о входных данных: какие столбцы есть в таблице, их названия и какую информацию они несут. Так работа выглядит презентабельно. Подробнее смотри методичку по оформлению проектов. Она располагается в Notion в разделе "Как оформлять проект".

</div>

- Таблица содержит 12 столбцов и 21525 строк c типом данных в скобках:
     - children — количество детей в семье
     - days_employed — общий трудовой стаж в днях
     - dob_years — возраст клиента в годах
     - education — уровень образования клиента
     - education_id — идентификатор уровня образования
     - family_status — семейное положение
     - family_status_id — идентификатор семейного положения
     - gender — пол клиента
     - income_type — тип занятости
     - debt — имел ли задолженность по возврату кредитов
     - total_income — ежемесячный доход
     - purpose — цель получения кредита

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера 2</b></font>

Успех: Вступление в работу очень важно. Так ты поясняешь то, чему она посвящена.

</div>

## Шаг 1. Откройте файл с данными и изучите общую информацию

<div class="alert alert-warning">
<font size="5"><b>Комментарий ревьюера</b></font>

Совет: Я заметил, что ячейки в твоей тетрадке начинаются не с 1. Перед отправкой работы рекомендую перезапускать ноутбук, чтобы убедиться, что все ячейки выполняются корректно.

</div>

Спасибо! Принял во внимание.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера 2</b></font>

Успех: Перезапуск позволяет обнаружить и исправить скрытые в коде ошибки. 

</div>

In [1]:
import pandas as pd
from pymystem3 import Mystem
m = Mystem()

data = pd.read_csv('/datasets/data.csv')
data.head(50)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля
20,1,-1311.604166,36,среднее,1,женат / замужем,0,M,сотрудник,0,209552.644578,недвижимость
21,1,-253.685166,33,среднее,1,гражданский брак,1,F,сотрудник,0,131812.203909,приобретение автомобиля
22,1,-1766.644138,24,среднее,1,гражданский брак,1,F,сотрудник,0,149681.140731,на покупку подержанного автомобиля
23,0,-272.981385,21,высшее,0,гражданский брак,1,M,сотрудник,0,128265.720871,сыграть свадьбу
24,1,338551.952911,57,среднее,1,Не женат / не замужем,4,F,пенсионер,0,290547.235997,операции с коммерческой недвижимостью
25,0,363548.489348,67,среднее,1,женат / замужем,0,M,пенсионер,0,55112.757732,покупка недвижимости
26,0,NaN,41,среднее,1,женат / замужем,0,M,госслужащий,0,NaN,образование
27,0,-529.191635,28,высшее,0,женат / замужем,0,M,сотрудник,0,308848.983691,строительство собственной недвижимости
28,1,-717.274324,26,высшее,0,женат / замужем,0,F,сотрудник,0,187863.237306,строительство собственной недвижимости
29,0,NaN,63,среднее,1,Не женат / не замужем,4,F,пенсионер,0,NaN,строительство жилой недвижимости
30,1,335581.668515,62,среднее,1,женат / замужем,0,F,пенсионер,0,171456.067993,операции с коммерческой недвижимостью
31,0,-1682.083438,47,начальное,3,женат / замужем,0,F,сотрудник,0,275485.684538,жилье
32,0,-4649.910832,34,СРЕДНЕЕ,1,гражданский брак,1,F,сотрудник,1,139057.464207,на проведение свадьбы
33,0,-1548.637544,48,среднее,1,женат / замужем,0,F,компаньон,0,157245.786233,покупка жилья
34,0,-4488.067031,35,среднее,1,женат / замужем,0,F,сотрудник,0,104660.449203,операции со своей недвижимостью
35,0,394021.072184,68,среднее,1,гражданский брак,1,M,пенсионер,0,77805.677436,на проведение свадьбы
36,0,-176.216688,33,среднее,1,Не женат / не замужем,4,M,сотрудник,0,138830.650734,автомобили
37,0,-6448.810860,43,ВЫСШЕЕ,0,гражданский брак,1,F,компаньон,0,154128.878672,приобретение автомобиля
38,0,-597.881827,25,высшее,0,Не женат / не замужем,4,M,сотрудник,1,192247.298639,образование
39,0,-650.587796,31,высшее,0,гражданский брак,1,F,компаньон,0,754240.797248,заняться образованием
40,0,-1030.362606,30,среднее,1,Не женат / не замужем,4,M,компаньон,0,142865.579146,покупка недвижимости
41,0,NaN,50,среднее,1,женат / замужем,0,F,госслужащий,0,NaN,сделка с подержанным автомобилем
42,0,-1257.496190,20,неоконченное высшее,2,Не женат / не замужем,4,F,сотрудник,0,82065.089021,получение образования
43,0,-4375.681384,43,неоконченное высшее,2,в разводе,3,F,компаньон,0,272957.133509,приобретение автомобиля
44,1,-1362.041728,26,СРЕДНЕЕ,1,женат / замужем,0,F,сотрудник,0,100780.496749,на покупку своего автомобиля
45,1,-1039.451741,49,среднее,1,Не женат / не замужем,4,F,сотрудник,0,106385.919724,заняться образованием
46,2,-2262.712304,37,среднее,1,женат / замужем,0,F,компаньон,0,182682.459898,сделка с подержанным автомобилем
47,1,-2689.137274,33,высшее,0,гражданский брак,1,M,госслужащий,0,356277.909345,на проведение свадьбы
48,0,-3341.067886,45,среднее,1,женат / замужем,0,F,сотрудник,0,162065.516450,строительство собственной недвижимости
49,0,-1181.443228,54,среднее,1,женат / замужем,0,F,сотрудник,0,44591.806888,автомобиль

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       19351 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        19351 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

In [3]:
data.describe()

,children,days_employed,dob_years,education_id,family_status_id,debt,total_income
count,21525.000000,19351.000000,21525.000000,21525.000000,21525.000000,21525.000000,1.935100e+04
mean,0.538908,63046.497661,43.293380,0.817236,0.972544,0.080883,1.674223e+05
std,1.381587,140827.311974,12.574584,0.548138,1.420324,0.272661,1.029716e+05
min,-1.000000,-18388.949901,0.000000,0.000000,0.000000,0.000000,2.066726e+04
25%,0.000000,-2747.423625,33.000000,1.000000,0.000000,0.000000,1.030532e+05
50%,0.000000,-1203.369529,42.000000,1.000000,0.000000,0.000000,1.450179e+05
75%,1.000000,-291.095954,53.000000,1.000000,1.000000,0.000000,2.034351e+05
max,20.000000,401755.400475,75.000000,4.000000,4.000000,1.000000,2.265604e+06

**Вывод**


В столбце days_employed встречаются отрицательные значени. Также в этом столбце есть пропущенные значения NaN. Еще NaN встречается в столбце total_income. Их нужно заполнить и понять причину возникновения. total_income округлим и переведем в int, для удобства. Приведем education к общему регистру. Максимальное и минимальной количество детей, возможно опечатки. В столбце days_employed стаж у пенсионеров > 1000 лет.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Подумай также о возможных причинах появления пропусков, а также о том, являются ли они случайными или нет. Можно высказать предварительные варианты их обработки. 

Первый взгляд на таблицу выполнен.

</div>

## Шаг 2. Предобработка данных

### Обработка пропусков

In [4]:
data[data['days_employed'].isna()].count() # узнаем количество пропущенных значений

children            2174
days_employed          0
dob_years           2174
education           2174
education_id        2174
family_status       2174
family_status_id    2174
gender              2174
income_type         2174
debt                2174
total_income           0
purpose             2174
dtype: int64

In [5]:
total_income_group_mean = data.groupby('income_type')['total_income'].transform('mean') # средний доход по типу занятости  
data['total_income'].fillna(total_income_group_mean, inplace=True) # заменяем NaN в 'total_income' на средний доход по типу занятости 

data['days_employed'] = data['days_employed'].apply(abs) # избавляемся от отрицательных значений в 'days_employed'

days_employed_group_mean = data.groupby('income_type')['days_employed'].transform('mean') # среднее 'days_employed' по типу занятости  
data['days_employed'].fillna(days_employed_group_mean, inplace=True)
data.tail(50)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
21475,0,365213.306266,52,среднее,1,женат / замужем,0,F,пенсионер,1,48239.310903,свой автомобиль
21476,0,2539.502794,52,высшее,0,женат / замужем,0,M,компаньон,0,527452.833253,операции со своей недвижимостью
21477,0,1628.432350,54,среднее,1,гражданский брак,1,F,сотрудник,0,71733.906470,на проведение свадьбы
21478,1,921.332705,28,Высшее,0,женат / замужем,0,F,сотрудник,0,181185.864790,свой автомобиль
21479,0,685.565994,26,среднее,1,женат / замужем,0,M,сотрудник,0,171504.352534,покупка жилья для сдачи
21480,0,8799.354717,45,высшее,0,Не женат / не замужем,4,F,сотрудник,0,146945.045428,ремонт жилью
21481,0,829.519627,30,неоконченное высшее,2,гражданский брак,1,M,сотрудник,0,440470.880955,на покупку автомобиля
21482,1,865.081118,25,среднее,1,женат / замужем,0,F,компаньон,0,94065.031245,свой автомобиль
21483,2,2917.035232,38,начальное,3,гражданский брак,1,F,сотрудник,1,77417.560520,операции с недвижимостью
21484,3,968.718123,35,среднее,1,женат / замужем,0,M,сотрудник,0,95667.452395,жилье
21485,0,363996.449108,59,высшее,0,женат / замужем,0,F,пенсионер,0,267000.734155,на покупку подержанного автомобиля
21486,0,1614.022809,36,СРЕДНЕЕ,1,женат / замужем,0,F,сотрудник,1,80763.856017,автомобиль
21487,0,2376.789344,30,СРЕДНЕЕ,1,гражданский брак,1,F,сотрудник,0,87834.565090,недвижимость
21488,0,354.755760,35,высшее,0,Не женат / не замужем,4,F,компаньон,0,128897.486083,недвижимость
21489,2,2111.524398,47,Среднее,1,женат / замужем,0,M,компаньон,0,202417.461462,сделка с автомобилем
21490,2,1867.006757,32,среднее,1,женат / замужем,0,F,сотрудник,0,34767.965495,операции с коммерческой недвижимостью
21491,20,173.954460,27,среднее,1,женат / замужем,0,F,сотрудник,0,155520.899688,на покупку подержанного автомобиля
21492,0,1618.645283,54,среднее,1,женат / замужем,0,M,компаньон,0,295234.214807,покупка жилой недвижимости
21493,1,1214.858885,38,среднее,1,женат / замужем,0,F,сотрудник,0,147502.599329,покупка жилья для семьи
21494,0,960.095747,39,среднее,1,гражданский брак,1,M,компаньон,1,176369.594491,дополнительное образование
21495,1,2326.499216,50,среднее,1,гражданский брак,1,F,сотрудник,0,161380.260488,свадьба
21496,1,759.680851,31,среднее,1,женат / замужем,0,F,сотрудник,0,119392.620079,на покупку автомобиля
21497,0,2111.524398,48,ВЫСШЕЕ,0,женат / замужем,0,F,компаньон,0,202417.461462,строительство недвижимости
21498,1,1330.627998,32,среднее,1,гражданский брак,1,M,сотрудник,0,240767.575887,сыграть свадьбу
21499,0,9929.015065,57,среднее,1,гражданский брак,1,M,компаньон,0,157553.158589,свадьба
21500,0,578.082757,26,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,77813.293365,операции с коммерческой недвижимостью
21501,0,334343.096304,57,среднее,1,женат / замужем,0,F,пенсионер,0,86232.126549,жилье
21502,1,2326.499216,42,среднее,1,женат / замужем,0,F,сотрудник,0,161380.260488,строительство жилой недвижимости
21503,0,3096.881131,58,среднее,1,женат / замужем,0,F,сотрудник,0,264250.997662,заняться образованием
21504,0,355235.728158,68,среднее,1,женат / замужем,0,F,пенсионер,0,80566.321329,дополнительное образование
21505,0,338904.866406,53,среднее,1,гражданский брак,1,M,пенсионер,0,75439.993167,сыграть свадьбу
21506,1,1556.249906,33,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,145541.993320,свадьба
21507,1,79.832064,32,среднее,1,гражданский брак,1,F,госслужащий,0,98180.279152,сделка с подержанным автомобилем
21508,0,386497.714078,62,среднее,1,женат / замужем,0,M,пенсионер,0,72638.590915,недвижимость
21509,0,362161.054124,59,высшее,0,женат / замужем,0,M,пенсионер,0,73029.059379,операции с недвижимостью
21510,2,2326.499216,28,среднее,1,женат / замужем,0,F,сотрудник,0,161380.260488,приобретение автомобиля
21511,0,612.569129,29,высшее,0,гражданский брак,1,F,сотрудник,1,140068.472941,покупка жилья для сдачи
21512,0,165.377752,26,высшее,0,Не женат / не замужем,4,M,компаньон,0,147301.457769,получение дополнительного образования
21513,0,1166.216789,35,среднее,1,женат / замужем,0,F,сотрудник,0,250986.142309,покупка жилья
21514,0,280.469996,27,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,355988.407188,строительство недвижимости
21515,1,467.685130,28,среднее,1,женат / замужем,0,F,сотрудник,1,109486.327999,заняться образованием
21516,0,914.391429,42,высшее,0,женат / замужем,0,F,компаньон,0,322807.776603,покупка своего жилья
21517,0,404.679034,42,высшее,0,гражданский брак,1,F,компаньон,0,178059.553491,на покупку своего автомобиля
21518,0,373995.710838,59,СРЕДНЕЕ,1,женат / замужем,0,F,пенсионер,0,153864.650328,сделка с автомобилем
21519,1,2351.431934,37,ученая степень,4,в разводе,3,M,сотрудник,0,115949.039788,покупка коммерческой недвижимости
21520,1,4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791.862382,операции с жильем
21521,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999.806512,сделка с автомобилем
21522,1,2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672.561153,недвижимость
21523,3,3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093.050500,на покупку своего автомобиля
21524,2,1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047.418899,на покупку автомобиля

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Соглашусь, тип занятости влияет на получаемый доход. Здорово, что ты заметил это и обработал пропуски таким способом. 

</div>

In [6]:
#dob_years_group_mean = data.groupby('income_type')['dob_years'].mean() # средний возраст по категории занятости
#data['dob_years'] = data['dob_years'].replace(0, dob_years_group_mean) # меняем 0 'dob_years' на средний возраст по категории занятости
#data[data['dob_years'] == 0].count()[0]

#data['dob_years'] = data.groupby('income_type')['dob_years'].mean().replace(0, dob_years_group_mean) # меняем 0 'dob_years' на средний возраст по категории занятости

dob_years_mean = data['dob_years'].mean() # средний возраст
data['dob_years'] = data['dob_years'].replace(0, int(dob_years_mean)) # заменим 0 на средний возраст

#data[data['dob_years'] == 0].count()[0] # проверяем количество 0

data['children'] = data['children'].apply(abs) # переведем отрицательное значение 'children' в положительное
data['children'] = data['children'].replace(20, 2) # заменим количество детей с 20 на 2

data.info()
data.tail(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       21525 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        21525 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
21475,0,365213.306266,52,среднее,1,женат / замужем,0,F,пенсионер,1,48239.310903,свой автомобиль
21476,0,2539.502794,52,высшее,0,женат / замужем,0,M,компаньон,0,527452.833253,операции со своей недвижимостью
21477,0,1628.432350,54,среднее,1,гражданский брак,1,F,сотрудник,0,71733.906470,на проведение свадьбы
21478,1,921.332705,28,Высшее,0,женат / замужем,0,F,сотрудник,0,181185.864790,свой автомобиль
21479,0,685.565994,26,среднее,1,женат / замужем,0,M,сотрудник,0,171504.352534,покупка жилья для сдачи
21480,0,8799.354717,45,высшее,0,Не женат / не замужем,4,F,сотрудник,0,146945.045428,ремонт жилью
21481,0,829.519627,30,неоконченное высшее,2,гражданский брак,1,M,сотрудник,0,440470.880955,на покупку автомобиля
21482,1,865.081118,25,среднее,1,женат / замужем,0,F,компаньон,0,94065.031245,свой автомобиль
21483,2,2917.035232,38,начальное,3,гражданский брак,1,F,сотрудник,1,77417.560520,операции с недвижимостью
21484,3,968.718123,35,среднее,1,женат / замужем,0,M,сотрудник,0,95667.452395,жилье
21485,0,363996.449108,59,высшее,0,женат / замужем,0,F,пенсионер,0,267000.734155,на покупку подержанного автомобиля
21486,0,1614.022809,36,СРЕДНЕЕ,1,женат / замужем,0,F,сотрудник,1,80763.856017,автомобиль
21487,0,2376.789344,30,СРЕДНЕЕ,1,гражданский брак,1,F,сотрудник,0,87834.565090,недвижимость
21488,0,354.755760,35,высшее,0,Не женат / не замужем,4,F,компаньон,0,128897.486083,недвижимость
21489,2,2111.524398,47,Среднее,1,женат / замужем,0,M,компаньон,0,202417.461462,сделка с автомобилем
21490,2,1867.006757,32,среднее,1,женат / замужем,0,F,сотрудник,0,34767.965495,операции с коммерческой недвижимостью
21491,2,173.954460,27,среднее,1,женат / замужем,0,F,сотрудник,0,155520.899688,на покупку подержанного автомобиля
21492,0,1618.645283,54,среднее,1,женат / замужем,0,M,компаньон,0,295234.214807,покупка жилой недвижимости
21493,1,1214.858885,38,среднее,1,женат / замужем,0,F,сотрудник,0,147502.599329,покупка жилья для семьи
21494,0,960.095747,39,среднее,1,гражданский брак,1,M,компаньон,1,176369.594491,дополнительное образование
21495,1,2326.499216,50,среднее,1,гражданский брак,1,F,сотрудник,0,161380.260488,свадьба
21496,1,759.680851,31,среднее,1,женат / замужем,0,F,сотрудник,0,119392.620079,на покупку автомобиля
21497,0,2111.524398,48,ВЫСШЕЕ,0,женат / замужем,0,F,компаньон,0,202417.461462,строительство недвижимости
21498,1,1330.627998,32,среднее,1,гражданский брак,1,M,сотрудник,0,240767.575887,сыграть свадьбу
21499,0,9929.015065,57,среднее,1,гражданский брак,1,M,компаньон,0,157553.158589,свадьба
21500,0,578.082757,26,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,77813.293365,операции с коммерческой недвижимостью
21501,0,334343.096304,57,среднее,1,женат / замужем,0,F,пенсионер,0,86232.126549,жилье
21502,1,2326.499216,42,среднее,1,женат / замужем,0,F,сотрудник,0,161380.260488,строительство жилой недвижимости
21503,0,3096.881131,58,среднее,1,женат / замужем,0,F,сотрудник,0,264250.997662,заняться образованием
21504,0,355235.728158,68,среднее,1,женат / замужем,0,F,пенсионер,0,80566.321329,дополнительное образование
21505,0,338904.866406,53,среднее,1,гражданский брак,1,M,пенсионер,0,75439.993167,сыграть свадьбу
21506,1,1556.249906,33,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,145541.993320,свадьба
21507,1,79.832064,32,среднее,1,гражданский брак,1,F,госслужащий,0,98180.279152,сделка с подержанным автомобилем
21508,0,386497.714078,62,среднее,1,женат / замужем,0,M,пенсионер,0,72638.590915,недвижимость
21509,0,362161.054124,59,высшее,0,женат / замужем,0,M,пенсионер,0,73029.059379,операции с недвижимостью
21510,2,2326.499216,28,среднее,1,женат / замужем,0,F,сотрудник,0,161380.260488,приобретение автомобиля
21511,0,612.569129,29,высшее,0,гражданский брак,1,F,сотрудник,1,140068.472941,покупка жилья для сдачи
21512,0,165.377752,26,высшее,0,Не женат / не замужем,4,M,компаньон,0,147301.457769,получение дополнительного образования
21513,0,1166.216789,35,среднее,1,женат / замужем,0,F,сотрудник,0,250986.142309,покупка жилья
21514,0,280.469996,27,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,355988.407188,строительство недвижимости
21515,1,467.685130,28,среднее,1,женат / замужем,0,F,сотрудник,1,109486.327999,заняться образованием
21516,0,914.391429,42,высшее,0,женат / замужем,0,F,компаньон,0,322807.776603,покупка своего жилья
21517,0,404.679034,42,высшее,0,гражданский брак,1,F,компаньон,0,178059.553491,на покупку своего автомобиля
21518,0,373995.710838,59,СРЕДНЕЕ,1,женат / замужем,0,F,пенсионер,0,153864.650328,сделка с автомобилем
21519,1,2351.431934,37,ученая степень,4,в разводе,3,M,сотрудник,0,115949.039788,покупка коммерческой недвижимости
21520,1,4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791.862382,операции с жильем
21521,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999.806512,сделка с автомобилем
21522,1,2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672.561153,недвижимость
21523,3,3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093.050500,на покупку своего автомобиля
21524,2,1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047.418899,на покупку автомобиля

**Вывод**

Заменили пропущенные значения по доходу на среднее для каждой категории занятости (Я думаю так будет точнее). Избавились от отрицательных значений в трудовом стаже, заполнили пропуски средним значение по категории занятости. Возможно клиенты не указывали свой возравст и доход. У пенсионеров получился средний стаж 365000 дней. Этот столбец для решения задачи нам не пригодится, но об ошибке необходимо предупредить. Знасения 0 в столбце возраст заменил на среднее по столбцу (хотел заменить на среднее по категории занятости, но, почемуто не получилось. Код закоментировал, может подскажете, где ошибка). Исправили количество детей с 20 на 2 (скорее всего опечатка).

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Классно, что ты также заметил и ошибки в данных. Их исправление поможет нам увеличить точность последующего анализа. 

</div>

### Замена типа данных

In [7]:
data['total_income'] = data['total_income'].astype('int') # преводим значения 'total_income' в челое int для удобства
data['dob_years'] = data['dob_years'].astype('int') # преводим значения 'dob_years' в int для удобства
data

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875,покупка жилья
1,1,4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080,приобретение автомобиля
2,0,5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885,покупка жилья
3,3,4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616,сыграть свадьбу
...,...,...,...,...,...,...,...,...,...,...,...,...
21520,1,4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791,операции с жильем
21521,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999,сделка с автомобилем
21522,1,2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672,недвижимость
21523,3,3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093,на покупку своего автомобиля
21524,2,1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047,на покупку автомобиля

**Вывод**

Преводим значения 'dob_years' и 'total_income' в int для удобства

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Исходя из общей информации о таблице, мы видим, что два столбца имеют вещественный тип данных, который и надо заменить на целочисленный. Эта замена произведена верно. Также хорошо бы освоить метод to_numeric() для будущих работ. 

</div>

### Обработка дубликатов

In [8]:
data['education'] = data['education'].str.lower() # привели 'education' к нижнему регистру
data.duplicated().sum() # посмотрим на суммарное количество дубликатов

71

In [9]:
data[data.duplicated(keep=False)].sort_values(by=['total_income', 'dob_years']) # посмотрим на дубликаты

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
17787,0,365003.491245,54,среднее,1,женат / замужем,0,F,пенсионер,0,137127,операции с жильем
21415,0,365003.491245,54,среднее,1,женат / замужем,0,F,пенсионер,0,137127,операции с жильем
3344,0,365003.491245,56,среднее,1,женат / замужем,0,F,пенсионер,0,137127,операции со своей недвижимостью
9627,0,365003.491245,56,среднее,1,женат / замужем,0,F,пенсионер,0,137127,операции со своей недвижимостью
13300,0,365003.491245,56,среднее,1,женат / замужем,0,F,пенсионер,0,137127,на покупку автомобиля
...,...,...,...,...,...,...,...,...,...,...,...,...
19369,0,2111.524398,45,среднее,1,гражданский брак,1,F,компаньон,0,202417,свадьба
9920,0,2111.524398,51,среднее,1,гражданский брак,1,F,компаньон,0,202417,на проведение свадьбы
15991,0,2111.524398,51,среднее,1,гражданский брак,1,F,компаньон,0,202417,на проведение свадьбы
2254,0,2111.524398,54,высшее,0,женат / замужем,0,M,компаньон,0,202417,операции с коммерческой недвижимостью
17379,0,2111.524398,54,высшее,0,женат / замужем,0,M,компаньон,0,202417,операции с коммерческой недвижимостью

In [10]:
data = data.drop_duplicates().reset_index() # удаляем дубликаты

In [11]:
data.duplicated().sum() # проверяем еще раз дубликаты

0

**Вывод**

Привели 'education' к нижнему регистру. Выявили и удалили дубликаты. Причина появления дублей, скорее всего, в работе скрипта. Человек несколько раз нажимал на отправку формы и форма отправлялась несколько раз.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Дубликаты вызывают смещение финальных результатов, поэтому их и надо удалять. Конечно, в данных нет уникального идентификатора, однако надо уметь удалять дубликаты. Метод drop_duplicates() использован верно.

</div>

### Лемматизация

In [12]:
data['purpose'].value_counts() # посмотрим на все цели кредита

свадьба                                   791
на проведение свадьбы                     768
сыграть свадьбу                           765
операции с недвижимостью                  675
покупка коммерческой недвижимости         661
операции с жильем                         652
покупка жилья для сдачи                   651
операции с коммерческой недвижимостью     650
покупка жилья                             646
жилье                                     646
покупка жилья для семьи                   638
строительство собственной недвижимости    635
недвижимость                              633
операции со своей недвижимостью           627
строительство жилой недвижимости          624
покупка недвижимости                      621
покупка своего жилья                      620
строительство недвижимости                619
ремонт жилью                              607
покупка жилой недвижимости                606
на покупку своего автомобиля              505
заняться высшим образованием              496
автомобиль                                494
сделка с подержанным автомобилем          486
на покупку подержанного автомобиля        478
свой автомобиль                           478
автомобили                                478
на покупку автомобиля                     471
приобретение автомобиля                   461
дополнительное образование                460
сделка с автомобилем                      455
высшее образование                        452
образование                               447
получение дополнительного образования     446
получение образования                     442
профильное образование                    436
получение высшего образования             426
заняться образованием                     408
Name: purpose, dtype: int64

In [13]:
from pymystem3 import Mystem
m = Mystem()
def purpose_lemmas(purpose):
     lemmas = m.lemmatize(purpose)  # лемматизировали цели кредита
     return lemmas                
data['purpose_lemmas'] = data['purpose'].apply(purpose_lemmas)
data.head(50)

,index,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose,purpose_lemmas
0,0,1,8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875,покупка жилья,"[покупка, , жилье, \n]"
1,1,1,4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080,приобретение автомобиля,"[приобретение, , автомобиль, \n]"
2,2,0,5623.422610,33,среднее,1,женат / замужем,0,M,сотрудник,0,145885,покупка жилья,"[покупка, , жилье, \n]"
3,3,3,4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628,дополнительное образование,"[дополнительный, , образование, \n]"
4,4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616,сыграть свадьбу,"[сыграть, , свадьба, \n]"
5,5,0,926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763,покупка жилья,"[покупка, , жилье, \n]"
6,6,0,2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525,операции с жильем,"[операция, , с, , жилье, \n]"
7,7,0,152.779569,50,среднее,1,женат / замужем,0,M,сотрудник,0,135823,образование,"[образование, \n]"
8,8,2,6929.865299,35,высшее,0,гражданский брак,1,F,сотрудник,0,95856,на проведение свадьбы,"[на, , проведение, , свадьба, \n]"
9,9,0,2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425,покупка жилья для семьи,"[покупка, , жилье, , для, , семья, \n]"
10,10,2,4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943,покупка недвижимости,"[покупка, , недвижимость, \n]"
11,11,0,792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069,покупка коммерческой недвижимости,"[покупка, , коммерческий, , недвижимость, \n]"
12,12,0,365003.491245,65,среднее,1,гражданский брак,1,M,пенсионер,0,137127,сыграть свадьбу,"[сыграть, , свадьба, \n]"
13,13,0,1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458,приобретение автомобиля,"[приобретение, , автомобиль, \n]"
14,14,0,1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127,покупка жилой недвижимости,"[покупка, , жилой, , недвижимость, \n]"
15,15,1,972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост..."
16,16,0,1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202,недвижимость,"[недвижимость, \n]"
17,17,0,2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410,строительство недвижимости,"[строительство, , недвижимость, \n]"
18,18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823,на покупку подержанного автомобиля,"[на, , покупка, , подержать, , автомобиль, \n]"
19,19,0,10038.818549,48,среднее,1,в разводе,3,F,сотрудник,0,242831,на покупку своего автомобиля,"[на, , покупка, , свой, , автомобиль, \n]"
20,20,1,1311.604166,36,среднее,1,женат / замужем,0,M,сотрудник,0,209552,недвижимость,"[недвижимость, \n]"
21,21,1,253.685166,33,среднее,1,гражданский брак,1,F,сотрудник,0,131812,приобретение автомобиля,"[приобретение, , автомобиль, \n]"
22,22,1,1766.644138,24,среднее,1,гражданский брак,1,F,сотрудник,0,149681,на покупку подержанного автомобиля,"[на, , покупка, , подержать, , автомобиль, \n]"
23,23,0,272.981385,21,высшее,0,гражданский брак,1,M,сотрудник,0,128265,сыграть свадьбу,"[сыграть, , свадьба, \n]"
24,24,1,338551.952911,57,среднее,1,Не женат / не замужем,4,F,пенсионер,0,290547,операции с коммерческой недвижимостью,"[операция, , с, , коммерческий, , недвижимо..."
25,25,0,363548.489348,67,среднее,1,женат / замужем,0,M,пенсионер,0,55112,покупка недвижимости,"[покупка, , недвижимость, \n]"
26,26,0,3399.896902,41,среднее,1,женат / замужем,0,M,госслужащий,0,170898,образование,"[образование, \n]"
27,27,0,529.191635,28,высшее,0,женат / замужем,0,M,сотрудник,0,308848,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост..."
28,28,1,717.274324,26,высшее,0,женат / замужем,0,F,сотрудник,0,187863,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост..."
29,29,0,365003.491245,63,среднее,1,Не женат / не замужем,4,F,пенсионер,0,137127,строительство жилой недвижимости,"[строительство, , жилой, , недвижимость, \n]"
30,30,1,335581.668515,62,среднее,1,женат / замужем,0,F,пенсионер,0,171456,операции с коммерческой недвижимостью,"[операция, , с, , коммерческий, , недвижимо..."
31,31,0,1682.083438,47,начальное,3,женат / замужем,0,F,сотрудник,0,275485,жилье,"[жилье, \n]"
32,32,0,4649.910832,34,среднее,1,гражданский брак,1,F,сотрудник,1,139057,на проведение свадьбы,"[на, , проведение, , свадьба, \n]"
33,33,0,1548.637544,48,среднее,1,женат / замужем,0,F,компаньон,0,157245,покупка жилья,"[покупка, , жилье, \n]"
34,34,0,4488.067031,35,среднее,1,женат / замужем,0,F,сотрудник,0,104660,операции со своей недвижимостью,"[операция, , со, , свой, , недвижимость, \n]"
35,35,0,394021.072184,68,среднее,1,гражданский брак,1,M,пенсионер,0,77805,на проведение свадьбы,"[на, , проведение, , свадьба, \n]"
36,36,0,176.216688,33,среднее,1,Не женат / не замужем,4,M,сотрудник,0,138830,автомобили,"[автомобиль, \n]"
37,37,0,6448.810860,43,высшее,0,гражданский брак,1,F,компаньон,0,154128,приобретение автомобиля,"[приобретение, , автомобиль, \n]"
38,38,0,597.881827,25,высшее,0,Не женат / не замужем,4,M,сотрудник,1,192247,образование,"[образование, \n]"
39,39,0,650.587796,31,высшее,0,гражданский брак,1,F,компаньон,0,754240,заняться образованием,"[заниматься, , образование, \n]"
40,40,0,1030.362606,30,среднее,1,Не женат / не замужем,4,M,компаньон,0,142865,покупка недвижимости,"[покупка, , недвижимость, \n]"
41,41,0,3399.896902,50,среднее,1,женат / замужем,0,F,госслужащий,0,170898,сделка с подержанным автомобилем,"[сделка, , с, , подержанный, , автомобиль, \n]"
42,42,0,1257.496190,20,неоконченное высшее,2,Не женат / не замужем,4,F,сотрудник,0,82065,получение образования,"[получение, , образование, \n]"
43,43,0,4375.681384,43,неоконченное высшее,2,в разводе,3,F,компаньон,0,272957,приобретение автомобиля,"[приобретение, , автомобиль, \n]"
44,44,1,1362.041728,26,среднее,1,женат / замужем,0,F,сотрудник,0,100780,на покупку своего автомобиля,"[на, , покупка, , свой, , автомобиль, \n]"
45,45,1,1039.451741,49,среднее,1,Не женат / не замужем,4,F,сотрудник,0,106385,заняться образованием,"[заниматься, , образование, \n]"
46,46,2,2262.712304,37,среднее,1,женат / замужем,0,F,компаньон,0,182682,сделка с подержанным автомобилем,"[сделка, , с, , подержанный, , автомобиль, \n]"
47,47,1,2689.137274,33,высшее,0,гражданский брак,1,M,госслужащий,0,356277,на проведение свадьбы,"[на, , проведение, , свадьба, \n]"
48,48,0,3341.067886,45,среднее,1,женат / замужем,0,F,сотрудник,0,162065,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост..."
49,49,0,1181.443228,54,среднее,1,женат / замужем,0,F,сотрудник,0,44591,автомобиль,"[автомобиль, \n]"

In [14]:
data['purpose_lemmas'].value_counts() # выделим топ целей (автомобиль, свадьба, недвижимость, образование)

[автомобиль, \n]                                          972
[свадьба, \n]                                             791
[на,  , проведение,  , свадьба, \n]                       768
[сыграть,  , свадьба, \n]                                 765
[операция,  , с,  , недвижимость, \n]                     675
[покупка,  , коммерческий,  , недвижимость, \n]           661
[операция,  , с,  , жилье, \n]                            652
[покупка,  , жилье,  , для,  , сдача, \n]                 651
[операция,  , с,  , коммерческий,  , недвижимость, \n]    650
[покупка,  , жилье, \n]                                   646
[жилье, \n]                                               646
[покупка,  , жилье,  , для,  , семья, \n]                 638
[строительство,  , собственный,  , недвижимость, \n]      635
[недвижимость, \n]                                        633
[операция,  , со,  , свой,  , недвижимость, \n]           627
[строительство,  , жилой,  , недвижимость, \n]            624
[покупка,  , недвижимость, \n]                            621
[покупка,  , свой,  , жилье, \n]                          620
[строительство,  , недвижимость, \n]                      619
[ремонт,  , жилье, \n]                                    607
[покупка,  , жилой,  , недвижимость, \n]                  606
[на,  , покупка,  , свой,  , автомобиль, \n]              505
[заниматься,  , высокий,  , образование, \n]              496
[сделка,  , с,  , подержанный,  , автомобиль, \n]         486
[свой,  , автомобиль, \n]                                 478
[на,  , покупка,  , подержать,  , автомобиль, \n]         478
[на,  , покупка,  , автомобиль, \n]                       471
[приобретение,  , автомобиль, \n]                         461
[дополнительный,  , образование, \n]                      460
[сделка,  , с,  , автомобиль, \n]                         455
[высокий,  , образование, \n]                             452
[образование, \n]                                         447
[получение,  , дополнительный,  , образование, \n]        446
[получение,  , образование, \n]                           442
[профильный,  , образование, \n]                          436
[получение,  , высокий,  , образование, \n]               426
[заниматься,  , образование, \n]                          408
Name: purpose_lemmas, dtype: int64

**Вывод**

Лемматизацию записал в новый столбец для дальнейшей категоризации. Перед лемматизацией вывел цели для ознакомления. После лемматизации веделил основные категории (автомобиль, свадьба, недвижимость, образование).

### Категоризация данных

In [15]:
def purpose_cat(purpose):    # присвоили категории всем клиентам по целям
    if 'автомобиль'in purpose:
        return 'авто'
    elif 'свадьба' in purpose:
        return 'свадьба'
    elif 'недвижимость' in purpose or 'жилье' in purpose:
        return 'недвижимость'
    elif 'образование' in purpose:
        return 'образование'
    else:
        return 'другое'
data['purpose_cat'] = data['purpose_lemmas'].apply(purpose_cat)
data['purpose_cat'].value_counts()

недвижимость    10811
авто             4306
образование      4013
свадьба          2324
Name: purpose_cat, dtype: int64

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Круто, ты сделал самую сложную часть проекта. Использовал нужные методы, и даже провел группировку с помощью собственной функции. Выбор основных целей кредитов обоснован ранее. 

</div>

In [16]:
data['dob_years'].sort_values() # смотрим возраст заемщиков

5558     19
12998    19
9208     19
20166    19
2725     19
         ..
4891     74
12297    74
3458     74
2557     74
8870     75
Name: dob_years, Length: 21454, dtype: int64

In [17]:
def dob_years_group(age): # категории по возрасту
    if 18 <= age <= 35:
        return 'молодые'
    if 36 <= age <= 65:
        return 'средний возраст'
    if age > 65:
        return 'пенсионеры'
dob_years_group(66)

'пенсионеры'

In [18]:
data['dob_years_group'] = data['dob_years'].apply(dob_years_group)
data.head(50)

,index,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose,purpose_lemmas,purpose_cat,dob_years_group
0,0,1,8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875,покупка жилья,"[покупка, , жилье, \n]",недвижимость,средний возраст
1,1,1,4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,средний возраст
2,2,0,5623.422610,33,среднее,1,женат / замужем,0,M,сотрудник,0,145885,покупка жилья,"[покупка, , жилье, \n]",недвижимость,молодые
3,3,3,4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628,дополнительное образование,"[дополнительный, , образование, \n]",образование,молодые
4,4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616,сыграть свадьбу,"[сыграть, , свадьба, \n]",свадьба,средний возраст
5,5,0,926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763,покупка жилья,"[покупка, , жилье, \n]",недвижимость,молодые
6,6,0,2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525,операции с жильем,"[операция, , с, , жилье, \n]",недвижимость,средний возраст
7,7,0,152.779569,50,среднее,1,женат / замужем,0,M,сотрудник,0,135823,образование,"[образование, \n]",образование,средний возраст
8,8,2,6929.865299,35,высшее,0,гражданский брак,1,F,сотрудник,0,95856,на проведение свадьбы,"[на, , проведение, , свадьба, \n]",свадьба,молодые
9,9,0,2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425,покупка жилья для семьи,"[покупка, , жилье, , для, , семья, \n]",недвижимость,средний возраст
10,10,2,4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943,покупка недвижимости,"[покупка, , недвижимость, \n]",недвижимость,средний возраст
11,11,0,792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069,покупка коммерческой недвижимости,"[покупка, , коммерческий, , недвижимость, \n]",недвижимость,средний возраст
12,12,0,365003.491245,65,среднее,1,гражданский брак,1,M,пенсионер,0,137127,сыграть свадьбу,"[сыграть, , свадьба, \n]",свадьба,средний возраст
13,13,0,1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,средний возраст
14,14,0,1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127,покупка жилой недвижимости,"[покупка, , жилой, , недвижимость, \n]",недвижимость,средний возраст
15,15,1,972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост...",недвижимость,молодые
16,16,0,1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202,недвижимость,"[недвижимость, \n]",недвижимость,молодые
17,17,0,2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410,строительство недвижимости,"[строительство, , недвижимость, \n]",недвижимость,молодые
18,18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823,на покупку подержанного автомобиля,"[на, , покупка, , подержать, , автомобиль, \n]",авто,средний возраст
19,19,0,10038.818549,48,среднее,1,в разводе,3,F,сотрудник,0,242831,на покупку своего автомобиля,"[на, , покупка, , свой, , автомобиль, \n]",авто,средний возраст
20,20,1,1311.604166,36,среднее,1,женат / замужем,0,M,сотрудник,0,209552,недвижимость,"[недвижимость, \n]",недвижимость,средний возраст
21,21,1,253.685166,33,среднее,1,гражданский брак,1,F,сотрудник,0,131812,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,молодые
22,22,1,1766.644138,24,среднее,1,гражданский брак,1,F,сотрудник,0,149681,на покупку подержанного автомобиля,"[на, , покупка, , подержать, , автомобиль, \n]",авто,молодые
23,23,0,272.981385,21,высшее,0,гражданский брак,1,M,сотрудник,0,128265,сыграть свадьбу,"[сыграть, , свадьба, \n]",свадьба,молодые
24,24,1,338551.952911,57,среднее,1,Не женат / не замужем,4,F,пенсионер,0,290547,операции с коммерческой недвижимостью,"[операция, , с, , коммерческий, , недвижимо...",недвижимость,средний возраст
25,25,0,363548.489348,67,среднее,1,женат / замужем,0,M,пенсионер,0,55112,покупка недвижимости,"[покупка, , недвижимость, \n]",недвижимость,пенсионеры
26,26,0,3399.896902,41,среднее,1,женат / замужем,0,M,госслужащий,0,170898,образование,"[образование, \n]",образование,средний возраст
27,27,0,529.191635,28,высшее,0,женат / замужем,0,M,сотрудник,0,308848,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост...",недвижимость,молодые
28,28,1,717.274324,26,высшее,0,женат / замужем,0,F,сотрудник,0,187863,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост...",недвижимость,молодые
29,29,0,365003.491245,63,среднее,1,Не женат / не замужем,4,F,пенсионер,0,137127,строительство жилой недвижимости,"[строительство, , жилой, , недвижимость, \n]",недвижимость,средний возраст
30,30,1,335581.668515,62,среднее,1,женат / замужем,0,F,пенсионер,0,171456,операции с коммерческой недвижимостью,"[операция, , с, , коммерческий, , недвижимо...",недвижимость,средний возраст
31,31,0,1682.083438,47,начальное,3,женат / замужем,0,F,сотрудник,0,275485,жилье,"[жилье, \n]",недвижимость,средний возраст
32,32,0,4649.910832,34,среднее,1,гражданский брак,1,F,сотрудник,1,139057,на проведение свадьбы,"[на, , проведение, , свадьба, \n]",свадьба,молодые
33,33,0,1548.637544,48,среднее,1,женат / замужем,0,F,компаньон,0,157245,покупка жилья,"[покупка, , жилье, \n]",недвижимость,средний возраст
34,34,0,4488.067031,35,среднее,1,женат / замужем,0,F,сотрудник,0,104660,операции со своей недвижимостью,"[операция, , со, , свой, , недвижимость, \n]",недвижимость,молодые
35,35,0,394021.072184,68,среднее,1,гражданский брак,1,M,пенсионер,0,77805,на проведение свадьбы,"[на, , проведение, , свадьба, \n]",свадьба,пенсионеры
36,36,0,176.216688,33,среднее,1,Не женат / не замужем,4,M,сотрудник,0,138830,автомобили,"[автомобиль, \n]",авто,молодые
37,37,0,6448.810860,43,высшее,0,гражданский брак,1,F,компаньон,0,154128,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,средний возраст
38,38,0,597.881827,25,высшее,0,Не женат / не замужем,4,M,сотрудник,1,192247,образование,"[образование, \n]",образование,молодые
39,39,0,650.587796,31,высшее,0,гражданский брак,1,F,компаньон,0,754240,заняться образованием,"[заниматься, , образование, \n]",образование,молодые
40,40,0,1030.362606,30,среднее,1,Не женат / не замужем,4,M,компаньон,0,142865,покупка недвижимости,"[покупка, , недвижимость, \n]",недвижимость,молодые
41,41,0,3399.896902,50,среднее,1,женат / замужем,0,F,госслужащий,0,170898,сделка с подержанным автомобилем,"[сделка, , с, , подержанный, , автомобиль, \n]",авто,средний возраст
42,42,0,1257.496190,20,неоконченное высшее,2,Не женат / не замужем,4,F,сотрудник,0,82065,получение образования,"[получение, , образование, \n]",образование,молодые
43,43,0,4375.681384,43,неоконченное высшее,2,в разводе,3,F,компаньон,0,272957,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,средний возраст
44,44,1,1362.041728,26,среднее,1,женат / замужем,0,F,сотрудник,0,100780,на покупку своего автомобиля,"[на, , покупка, , свой, , автомобиль, \n]",авто,молодые
45,45,1,1039.451741,49,среднее,1,Не женат / не замужем,4,F,сотрудник,0,106385,заняться образованием,"[заниматься, , образование, \n]",образование,средний возраст
46,46,2,2262.712304,37,среднее,1,женат / замужем,0,F,компаньон,0,182682,сделка с подержанным автомобилем,"[сделка, , с, , подержанный, , автомобиль, \n]",авто,средний возраст
47,47,1,2689.137274,33,высшее,0,гражданский брак,1,M,госслужащий,0,356277,на проведение свадьбы,"[на, , проведение, , свадьба, \n]",свадьба,молодые
48,48,0,3341.067886,45,среднее,1,женат / замужем,0,F,сотрудник,0,162065,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост...",недвижимость,средний возраст
49,49,0,1181.443228,54,среднее,1,женат / замужем,0,F,сотрудник,0,44591,автомобиль,"[автомобиль, \n]",авто,средний возраст

In [19]:
data['total_income'].sort_values() # смотрим разброс доходов

14555      20667
12983      21205
16138      21367
1598       21695
14247      21895
          ...
17137    1711309
20742    1715018
9159     1726276
19548    2200852
12390    2265604
Name: total_income, Length: 21454, dtype: int64

In [20]:
def total_income_group(income): # разбиваем на категории по доходу
    if income <= 60000:
        return 'доход низкий'
    elif income <= 120000:
        return 'доход средний'
    elif income <= 180000:
        return 'доход выше среднего'
    elif income > 180000:
        return 'доход высокий'
data['total_income_group'] = data['total_income'].apply(total_income_group)
data.head(50)

,index,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose,purpose_lemmas,purpose_cat,dob_years_group,total_income_group
0,0,1,8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875,покупка жилья,"[покупка, , жилье, \n]",недвижимость,средний возраст,доход высокий
1,1,1,4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,средний возраст,доход средний
2,2,0,5623.422610,33,среднее,1,женат / замужем,0,M,сотрудник,0,145885,покупка жилья,"[покупка, , жилье, \n]",недвижимость,молодые,доход выше среднего
3,3,3,4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628,дополнительное образование,"[дополнительный, , образование, \n]",образование,молодые,доход высокий
4,4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616,сыграть свадьбу,"[сыграть, , свадьба, \n]",свадьба,средний возраст,доход выше среднего
5,5,0,926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763,покупка жилья,"[покупка, , жилье, \n]",недвижимость,молодые,доход высокий
6,6,0,2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525,операции с жильем,"[операция, , с, , жилье, \n]",недвижимость,средний возраст,доход высокий
7,7,0,152.779569,50,среднее,1,женат / замужем,0,M,сотрудник,0,135823,образование,"[образование, \n]",образование,средний возраст,доход выше среднего
8,8,2,6929.865299,35,высшее,0,гражданский брак,1,F,сотрудник,0,95856,на проведение свадьбы,"[на, , проведение, , свадьба, \n]",свадьба,молодые,доход средний
9,9,0,2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425,покупка жилья для семьи,"[покупка, , жилье, , для, , семья, \n]",недвижимость,средний возраст,доход выше среднего
10,10,2,4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943,покупка недвижимости,"[покупка, , недвижимость, \n]",недвижимость,средний возраст,доход средний
11,11,0,792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069,покупка коммерческой недвижимости,"[покупка, , коммерческий, , недвижимость, \n]",недвижимость,средний возраст,доход средний
12,12,0,365003.491245,65,среднее,1,гражданский брак,1,M,пенсионер,0,137127,сыграть свадьбу,"[сыграть, , свадьба, \n]",свадьба,средний возраст,доход выше среднего
13,13,0,1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,средний возраст,доход выше среднего
14,14,0,1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127,покупка жилой недвижимости,"[покупка, , жилой, , недвижимость, \n]",недвижимость,средний возраст,доход выше среднего
15,15,1,972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост...",недвижимость,молодые,доход средний
16,16,0,1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202,недвижимость,"[недвижимость, \n]",недвижимость,молодые,доход высокий
17,17,0,2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410,строительство недвижимости,"[строительство, , недвижимость, \n]",недвижимость,молодые,доход средний
18,18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823,на покупку подержанного автомобиля,"[на, , покупка, , подержать, , автомобиль, \n]",авто,средний возраст,доход низкий
19,19,0,10038.818549,48,среднее,1,в разводе,3,F,сотрудник,0,242831,на покупку своего автомобиля,"[на, , покупка, , свой, , автомобиль, \n]",авто,средний возраст,доход высокий
20,20,1,1311.604166,36,среднее,1,женат / замужем,0,M,сотрудник,0,209552,недвижимость,"[недвижимость, \n]",недвижимость,средний возраст,доход высокий
21,21,1,253.685166,33,среднее,1,гражданский брак,1,F,сотрудник,0,131812,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,молодые,доход выше среднего
22,22,1,1766.644138,24,среднее,1,гражданский брак,1,F,сотрудник,0,149681,на покупку подержанного автомобиля,"[на, , покупка, , подержать, , автомобиль, \n]",авто,молодые,доход выше среднего
23,23,0,272.981385,21,высшее,0,гражданский брак,1,M,сотрудник,0,128265,сыграть свадьбу,"[сыграть, , свадьба, \n]",свадьба,молодые,доход выше среднего
24,24,1,338551.952911,57,среднее,1,Не женат / не замужем,4,F,пенсионер,0,290547,операции с коммерческой недвижимостью,"[операция, , с, , коммерческий, , недвижимо...",недвижимость,средний возраст,доход высокий
25,25,0,363548.489348,67,среднее,1,женат / замужем,0,M,пенсионер,0,55112,покупка недвижимости,"[покупка, , недвижимость, \n]",недвижимость,пенсионеры,доход низкий
26,26,0,3399.896902,41,среднее,1,женат / замужем,0,M,госслужащий,0,170898,образование,"[образование, \n]",образование,средний возраст,доход выше среднего
27,27,0,529.191635,28,высшее,0,женат / замужем,0,M,сотрудник,0,308848,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост...",недвижимость,молодые,доход высокий
28,28,1,717.274324,26,высшее,0,женат / замужем,0,F,сотрудник,0,187863,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост...",недвижимость,молодые,доход высокий
29,29,0,365003.491245,63,среднее,1,Не женат / не замужем,4,F,пенсионер,0,137127,строительство жилой недвижимости,"[строительство, , жилой, , недвижимость, \n]",недвижимость,средний возраст,доход выше среднего
30,30,1,335581.668515,62,среднее,1,женат / замужем,0,F,пенсионер,0,171456,операции с коммерческой недвижимостью,"[операция, , с, , коммерческий, , недвижимо...",недвижимость,средний возраст,доход выше среднего
31,31,0,1682.083438,47,начальное,3,женат / замужем,0,F,сотрудник,0,275485,жилье,"[жилье, \n]",недвижимость,средний возраст,доход высокий
32,32,0,4649.910832,34,среднее,1,гражданский брак,1,F,сотрудник,1,139057,на проведение свадьбы,"[на, , проведение, , свадьба, \n]",свадьба,молодые,доход выше среднего
33,33,0,1548.637544,48,среднее,1,женат / замужем,0,F,компаньон,0,157245,покупка жилья,"[покупка, , жилье, \n]",недвижимость,средний возраст,доход выше среднего
34,34,0,4488.067031,35,среднее,1,женат / замужем,0,F,сотрудник,0,104660,операции со своей недвижимостью,"[операция, , со, , свой, , недвижимость, \n]",недвижимость,молодые,доход средний
35,35,0,394021.072184,68,среднее,1,гражданский брак,1,M,пенсионер,0,77805,на проведение свадьбы,"[на, , проведение, , свадьба, \n]",свадьба,пенсионеры,доход средний
36,36,0,176.216688,33,среднее,1,Не женат / не замужем,4,M,сотрудник,0,138830,автомобили,"[автомобиль, \n]",авто,молодые,доход выше среднего
37,37,0,6448.810860,43,высшее,0,гражданский брак,1,F,компаньон,0,154128,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,средний возраст,доход выше среднего
38,38,0,597.881827,25,высшее,0,Не женат / не замужем,4,M,сотрудник,1,192247,образование,"[образование, \n]",образование,молодые,доход высокий
39,39,0,650.587796,31,высшее,0,гражданский брак,1,F,компаньон,0,754240,заняться образованием,"[заниматься, , образование, \n]",образование,молодые,доход высокий
40,40,0,1030.362606,30,среднее,1,Не женат / не замужем,4,M,компаньон,0,142865,покупка недвижимости,"[покупка, , недвижимость, \n]",недвижимость,молодые,доход выше среднего
41,41,0,3399.896902,50,среднее,1,женат / замужем,0,F,госслужащий,0,170898,сделка с подержанным автомобилем,"[сделка, , с, , подержанный, , автомобиль, \n]",авто,средний возраст,доход выше среднего
42,42,0,1257.496190,20,неоконченное высшее,2,Не женат / не замужем,4,F,сотрудник,0,82065,получение образования,"[получение, , образование, \n]",образование,молодые,доход средний
43,43,0,4375.681384,43,неоконченное высшее,2,в разводе,3,F,компаньон,0,272957,приобретение автомобиля,"[приобретение, , автомобиль, \n]",авто,средний возраст,доход высокий
44,44,1,1362.041728,26,среднее,1,женат / замужем,0,F,сотрудник,0,100780,на покупку своего автомобиля,"[на, , покупка, , свой, , автомобиль, \n]",авто,молодые,доход средний
45,45,1,1039.451741,49,среднее,1,Не женат / не замужем,4,F,сотрудник,0,106385,заняться образованием,"[заниматься, , образование, \n]",образование,средний возраст,доход средний
46,46,2,2262.712304,37,среднее,1,женат / замужем,0,F,компаньон,0,182682,сделка с подержанным автомобилем,"[сделка, , с, , подержанный, , автомобиль, \n]",авто,средний возраст,доход высокий
47,47,1,2689.137274,33,высшее,0,гражданский брак,1,M,госслужащий,0,356277,на проведение свадьбы,"[на, , проведение, , свадьба, \n]",свадьба,молодые,доход высокий
48,48,0,3341.067886,45,среднее,1,женат / замужем,0,F,сотрудник,0,162065,строительство собственной недвижимости,"[строительство, , собственный, , недвижимост...",недвижимость,средний возраст,доход выше среднего
49,49,0,1181.443228,54,среднее,1,женат / замужем,0,F,сотрудник,0,44591,автомобиль,"[автомобиль, \n]",авто,средний возраст,доход низкий

<div class="alert alert-warning">
<font size="5"><b>Комментарий ревьюера</b></font>

Совет: Исходя из чего выбран именно такой способ категоризации столбца с доходами? Соглашусь с выбранным способом, но важно обосновать его выбор. 

</div>

**Вывод**

Произвели категоризацию данных по целям, возрасту и уровню дохода. Категории по возрасту и доходу искал в сети, данные разнятся, поэтому разбил на такие категории.

<div class="alert alert-danger">
<font size="5"><b>Комментарий ревьюера</b></font>

Ошибка: В данных есть словари. Попробуй их обнаружить и выделить. Это довольно распространенный способ хранения информации. Мне важно понять, что он тобой освоен. Заметь, что в основной таблице мы имеем по 2 параметра с образованием и семейным статусом. Именно по ним и стоит выделить словари. 

</div>

Правки по замечаниям ниже

In [21]:
education_cat = data.groupby(['education', 'education_id']).size().to_frame('count')
education_cat.sort_values(by='education_id')

                                  count
education           education_id
высшее              0              5250
среднее             1             15172
неоконченное высшее 2               744
начальное           3               282
ученая степень      4                 6

In [22]:
family_status_cat = data.groupby(['family_status', 'family_status_id']).size().to_frame('count')
family_status_cat.sort_values(by='family_status_id')

                                        count
family_status         family_status_id
женат / замужем       0                 12339
гражданский брак      1                  4151
вдовец / вдова        2                   959
в разводе             3                  1195
Не женат / не замужем 4                  2810

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера 2</b></font>

Успех: Отлично, словари сделаны. Теперь мы можем убрать текстовые параметры из основной таблицы, что увеличит эффективность работы с данными. 
</div>

## Шаг 3. Ответьте на вопросы

- Есть ли зависимость между наличием детей и возвратом кредита в срок?

In [23]:
data_pivot_children_debt = data.pivot_table(index = ['children'], values = 'debt').round(3) # сводная таблица по детям
data_pivot_children_debt.sort_values(by='debt')

           debt
children
5         0.000
0         0.075
3         0.082
1         0.092
2         0.095
4         0.098

**Вывод**

Из таблицы видно, что заемщики с количеством детей от 1 до 4 возвращают долг реже, чем заемщики без детей и с 5 детьми.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Вывод не противоречит полученному результату. 

</div>

- Есть ли зависимость между семейным положением и возвратом кредита в срок?

In [24]:
data_pivot_family_debt = data.pivot_table(index = ['family_status'], columns = 'debt', values = 'gender', aggfunc = 'count')
data_pivot_family_debt['family_debt'] = round(data_pivot_family_debt[1] / (data_pivot_family_debt[0] + data_pivot_family_debt[1]), 3)
data_pivot_family_debt.sort_values(by='family_debt') # сводная таблица по семейному положению

debt                       0    1  family_debt
family_status
вдовец / вдова           896   63        0.066
в разводе               1110   85        0.071
женат / замужем        11408  931        0.075
гражданский брак        3763  388        0.093
Не женат / не замужем   2536  274        0.098

**Вывод**

Заемщики не состоящие в официальных отношениях (Не женат / не замужем, гражданский брак) возвращают долг реже, чем остальные.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Подумай над причинами получения такого результата. 

</div>

- Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

In [25]:
data_pivot_income_debt = data.pivot_table(index = ['total_income_group'], columns = 'debt', values = 'gender', aggfunc = 'count')
data_pivot_income_debt['income_debt'] = round(data_pivot_income_debt[1] / (data_pivot_income_debt[0] + data_pivot_income_debt[1]), 3)
data_pivot_income_debt.sort_values(by='income_debt') # сводная таблица по уровню дохода

debt                    0    1  income_debt
total_income_group
доход низкий          757   49        0.061
доход высокий        6416  508        0.073
доход средний        5537  502        0.083
доход выше среднего  7003  682        0.089

**Вывод**

Люди с низким доходом чаще стараются возвращать кредит в срок. Реже возвращают люди с высоким доходом.

- Как разные цели кредита влияют на его возврат в срок?

In [26]:
data_pivot_purpose_debt = data.pivot_table(index = ['purpose_cat'], columns = 'debt', values = 'gender', aggfunc = 'count')
data_pivot_purpose_debt['purpose_debt'] = round(data_pivot_purpose_debt[1] / (data_pivot_purpose_debt[0] + data_pivot_purpose_debt[1]), 3)
data_pivot_purpose_debt.sort_values(by='purpose_debt') # сводная таблица по цели кредита

debt              0    1  purpose_debt
purpose_cat
недвижимость  10029  782         0.072
свадьба        2138  186         0.080
образование    3643  370         0.092
авто           3903  403         0.094

**Вывод**

Люди, берущие кредит на недвижимость, возвращают долг чаще, чем люди, берущие кредит, на образование или авто.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Здорово, что при анализе использован метод сводных таблиц. Он пригодится в дальнейших проектах.

Выводы сделаны по всем пунктам. 

</div>

## Шаг 4. Общий вывод

Идеальный заемщик: человек с 5-ю детьми, овдовевший, с низким уровнем дохода, берущий кредит на недвижимость.

<div class="alert alert-danger">
<font size="5"><b>Комментарий ревьюера</b></font>

Ошибка: Финальный вывод и есть главный результат твоей работы. Стоит писать его подробно по результатам проведенной работы. В нем можно приводить полученные в ходе работы значения. Также можно расписать все, что было сделано в работе.

</div>

<div>
<font size="3"><b>Вывод</b></font>
    
В ходе исследования мы изучили датафрейм, выявили ошибки и пропуски. Исправили и заполнили средними значениями по категориям. 
    
Выявили и удалили дубликаты. Произвели лемматизацию и категоризацию данных.
    
В ходе исследования выявили зависимость между наличием детей и возвратом кредита в срок. 
Заемщики с 5-ю детьми не имеют задолжностей. Заемщики без детей возвращаю кредиты чаще, чем заемщики с 1-4 детьми.
    
Также выяснили, что овдовевшие заемщики платят чаще, чем люди не имеющие официальных отношений.
    
Выявили зависимость между уровнем дохода и возвратом кредита в срок. Заемщики с низким и высоким доходом более ответственные, 
чем заемщики со средним доходом и доходом выше среднего.
    
Также на возват кредита в срок влияют и цели кредита. Кредит на недвижимость и свадьбу возвращают чаще, чем кредит на 
    образование и автомобиль.
</div>

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех: Выводы описаны грамотно. Приведены ответы на главные вопросы проекта. В выводах можно приводить полученные ранее значения, правильно. Здорово, что по каждому пункту работы приведен вывод.     

</div>

<div class="alert alert-info">
<font size="5"><b>Комментарий ревьюера</b></font>

Ты проделал большую работу, молодец! Ты овладел важными на данном этапе обучения инструментами, а также довольно качественно их используешь. Критических замечаний немного. Однако их важно исправить. Также есть несколько желтых комментариев. Думаю, исправить и их тебе не составит труда. Жду твою работу :)

</div>

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера 2</b></font>

Помарки исправлены, и теперь работа выполнена хорошо. Ты здорово поработал, молодец. Продолжай в том же духе! Успехов в дальнейших проектах :)

С наступающими праздниками!
</div>

## Чек-лист готовности проекта

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  открыт файл;
- [x]  файл изучен;
- [x]  определены пропущенные значения;
- [x]  заполнены пропущенные значения;
- [x]  есть пояснение, какие пропущенные значения обнаружены;
- [x]  описаны возможные причины появления пропусков в данных;
- [x]  объяснено, по какому принципу заполнены пропуски;
- [x]  заменен вещественный тип данных на целочисленный;
- [x]  есть пояснение, какой метод используется для изменения типа данных и почему;
- [x]  удалены дубликаты;
- [x]  есть пояснение, какой метод используется для поиска и удаления дубликатов;
- [x]  описаны возможные причины появления дубликатов в данных;
- [x]  выделены леммы в значениях столбца с целями получения кредита;
- [x]  описан процесс лемматизации;
- [x]  данные категоризированы;
- [x]  есть объяснение принципа категоризации данных;
- [x]  есть ответ на вопрос: "Есть ли зависимость между наличием детей и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Есть ли зависимость между семейным положением и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Есть ли зависимость между уровнем дохода и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Как разные цели кредита влияют на его возврат в срок?";
- [x]  в каждом этапе есть выводы;
- [x]  есть общий вывод.